### PR TITLE
Install redis package and start it

### PR DESCRIPTION
**Pull request by mrakitin**
This is an optional update to use in the future. Right now, only BMM is in need of that package (see https://github.com/NSLS-II-BMM/profile_collection/pull/11, where we install it via `bl-specific.sh`).

### CODE REVIEW

**Review by AbbyGi — APPROVED** [review]
I like these changes.

**Comment by mrakitin** [comment]
It would be great to test this configuration and verify it works fine. @AbbyGi, do you mind creating a separate branch in the BMM's `profile_collection` repo (no PR is needed) and point the CI to this PR branch instead of `main`? That way we can see the CI logs and validate the packages were installed and the services started. Thanks!

**Comment by mrakitin** [comment]
I am running a new test with the updates: https://dev.azure.com/nsls2/profile_collections/_build/results?buildId=1973&view=results.

**Review by AbbyGi — APPROVED** [review]
Looks good.

**Pull request merged**
